---
abstract: 'Perl interface to EZID API - http://ezid.cdlib.org/doc/apidoc.html'
author:
  - 'Julian <julian.maurice@biblibre.com>'
build_requires:
  ExtUtils::MakeMaker: 0
  Test::More: 1.001006
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.112621'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: EZID
no_index:
  directory:
    - t
    - inc
requires:
  Modern::Perl: 1.20140107
  String::Random: 0.22
version: 0.02
